# Generated by Django 3.1.13 on 2021-09-04 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_name', models.CharField(max_length=150)),
                ('surah_r_city', models.CharField(max_length=150)),
                ('surah_number', models.PositiveSmallIntegerField()),
                ('surah_ayahs_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_number', models.PositiveIntegerField()),
                ('ayah_text', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sura.sura')),
            ],
        ),
    ]
