# Generated by Django 3.1.13 on 2021-09-04 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='audio_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
